[package]
name = "lexer"
version = "0.1.0"
edition = "2024"

[dependencies]
#logos = { version = "0.15", features = ["debug"] }
logos = { version = "0.15" }
clap = { version = "4.5", features = ["derive"] }

[lib]
name = "lexer"
path = "src/lib.rs"