[package]
name = "codegen"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cool-wasm"
path = "src/main.rs"

[dependencies]
wasm-encoder = "0.245.1"
wit-component = "0.245.1"
wasi-preview1-component-adapter-provider = "42.0.1"
ir = { path = "../ir" }
lexer = { path = "../lexer" }
parser = { path = "../parser" }
semant = { path = "../semant" }
